name: notus
description: Platform-agnostic rich text document model based on Delta format and used in Zefyr editor.
version: 1.0.0-dev.4.0
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>
homepage: https://github.com/memspace/zefyr

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.14.6
  meta: ^1.1.0
  quill_delta: 
    git:
      url: https://github.com/nestuge/zefyr-1.git
      path: packages/quill-delta-dart
  quiver: ^3.0.0

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.16.0
