name: zefyr
description: Clean, minimalistic and collaboration-ready rich text editor for Flutter.

version: 1.0.0-dev.2.0

author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>
homepage: https://github.com/memspace/zefyr

environment:
  sdk: '>=2.10.0 <3.0.0'

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.14.6
  url_launcher: ^6.0.2
  quill_delta: 
    git:
      url: https://github.com/nestuge/zefyr-1.git
      path: packages/quill-delta-dart
  notus: 
    git:
      url: https://github.com/nestuge/zefyr-1.git
      path: packages/notus
  meta: ^1.1.0
  quiver: ^3.0.0
  characters: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.0.0
